extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 2020
  sourceType: module

env:
  node: true

plugins:
  - import

rules:
  no-console: off
  no-underscore-dangle: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true
  import/extensions:
    - error
    - always
    - ignorePackages: true
  import/prefer-default-export: off
